### ISSUE TITLE
train.py crashes 

### ISSUE THREAD

**Issue by PtrBld** [paviro/MMM-Facial-Recognition-Tools#1]
Hi,
when I try to start the training for my images I choose the "LBPHF (recommended)" option after that it reads my images but chrashes with: 
`Training model...
Traceback (most recent call last):
  File "train.py", line 104, in <module>
    model = cv2.createLBPHFaceRecognizer()
AttributeError: 'module' object has no attribute 'createLBPHFaceRecognizer'`

Am I missing dependencies?

**Comment by paviro** [comment]
Hi,
Are you sure you installed all the opencv2 dependencies? If so try installing a newer version from source.

Cheers,
Paul

**Comment by paviro** [comment]
Are you using open cv3? If yes see http://answers.opencv.org/question/56859/opencv-300-facerecognizer-and-python-bindings/

**Comment by PtrBld** [comment]
You were right. I had to compile a newer version by myself.
Thank you!

**Comment by paviro** [comment]
Glad you could solve it! Could you may add something to the README in case someone else has the same problem?

**Comment by PtrBld** [comment]
Ok after spending some hours investigating I came to the result that I have to buy a new pi because rpi b+ is not fast enough... So I do not recommend to use this module with the rpi b+ at all. And therefore noone should need to go through the same problems as I did.

**Comment by paviro** [comment]
Does it work if you set a higher timeout for the recognition interval?

**Comment by PtrBld** [comment]
No it is a Problem with the open cv library itself

**Comment by paviro** [comment]
Ok.
