### ISSUE TITLE
Error when using capture and recognition unter raspi 3

### ISSUE THREAD

**Issue by feuermandel** [paviro/MMM-Facial-Recognition-Tools#17]
I read about raspi 3 is not supported (April last year). Has this fact changed over the last month or is support for raspi3 working again? If raspi 3 ist supported, can give some additionals details on the eroors, I encounter.

Best regards.

**Comment by randomstring** [comment]
MMM-Facial-Recognition-Tools works just fine on the raspberry pi 3. 

In fact, I used a pi3 for all the development work I did on MMM-Facial-Recognition-Tools.
