### ISSUE TITLE
No Module Named Builtins

### ISSUE THREAD

**Issue by BluishMechanismz** [paviro/MMM-Facial-Recognition-Tools#34]
Hi. I've been having the same problem others have been having, and even after installing future, the exact same problem continues. Reboots and reinstalls don't help either.

`Traceback (most recent call last):
  File "capture.py", line 18, in <module>
    import lib.capture as capture
  File "/home/pi/MMM-Facial-Recognition-Tools/lib/capture.py", line 12, in <module>
    from   builtins import input
ImportError: No module named builtins`

**Comment by randomstring** [comment]
If you installed the future module with pip, then I suspect you may have some issue with the version of python you're running not matching the environment your pip modules are getting installed into.

**Comment by MuhammadJamee** [comment]
Same problem for me, is there any solution?

**Comment by horstefan** [comment]
Same problem. any updates on this?

**Comment by aniiketdongare07** [comment]
Same issue, any updates?

**Comment by randomstring** [comment]
You all probably need to install the python 2 future package. Try:

`pip install future`
