### ISSUE TITLE
TypeError facerecognition.py

### ISSUE THREAD

**Issue by Eisblume77** [paviro/MMM-Facial-Recognition-Tools#36]
I generated train data, set the FACE_ALGORITM and the FACE_USERS but got a crash when I test with facerecognition.py:

**Remember to set the name list environment variable FACE_USERS
Using default FACE_ALGORITM: 1
Loading training data...
Training data loaded!
Strong:User1
No windowing system, writing face.jpg image
Traceback (most recent call last):
  File "facerecognition.py", line 153, in <module>
    clean_shutdown()
TypeError: clean_shutdown() takes exactly 2 arguments (0 given)**

Tried on RPi Model 3b+

Hope you can help me??

**Comment by randomstring** [comment]
The pertinent error here is: "No windowing system, writing face.jpg image"

I suspect you're trying to run from the command line and the program is trying to open a window to display the face.jpg image.
