### ISSUE TITLE
Facerecognision tester crash

### ISSUE THREAD

**Issue by Try2Fly** [paviro/MMM-Facial-Recognition-Tools#5]
Hi,

I get the following error as soon as a face is recognized in the tester module:

Traceback (most recent call last):
  File "/home/pi/MMM-Facial-Recognition-Tools-master/facerecognition_tester/facerecognition.py", line 67, in <module>
    cv2.putText(frame, config.personen[label - 1], (x - 3, y - 8), cv2.FONT_HERSHEY_SIMPLEX, 1.5, (255, 255, 255), 1)
IndexError: list index out of range

**Comment by paviro** [comment]
Have you added the array with the names to the config?

**Comment by Try2Fly** [comment]
No, forgot that. It is working now. But only with a webcam, not with the pi cam module. Is this possible with the pi cam module?

Thanks!

**Comment by paviro** [comment]
Should be. What happens when you execute `import picam` in a Python shell? Also make sure you have the latest version since I just added it a couple of days ago.

**Comment by Try2Fly** [comment]
ImportError: no module named picam

**Comment by paviro** [comment]
Try running `pip install picamera` before using it.

**Comment by Try2Fly** [comment]
seems like my pi camera stopped working. Cannot even use raspistill command to take single picture. Need to get the camera to work again first. If that works, I'll try this again. Thanks a lot!

**Comment by paviro** [comment]
Alright, good luck!

**Comment by Try2Fly** [comment]
Hi Paviro,

Turned out the camera connection on my pi was broken. Replaced it and the raspberry camera module now works. I was able to create a training file. However when starting the tester I get the following error:

Traceback (most recent call last):
  File "/home/pi/MagicMirror/modules/MMM-Facial-Recognition-Tools-master/facerecognition_tester/facerecognition.py", line 42, in <module>
    image = cv2.cvtColor(frame, cv2.COLOR_RGB2GRAY)
error: /build/opencv-ISmtkH/opencv-2.4.9.1+dfsg/modules/imgproc/src/color.cpp:3737: error: (-215) scn == 3 || scn == 4 in function cvtColor

Can you help me?

Update: I just connected a USB cam, and when using this, all works fine.

**Comment by ErikTh** [comment]
Just ran into the same issue. As I see it the facerecognition.py does not switch according to the camera type.

In facerecognition.py:
Line 37 replace
`capture = cv2.VideoCapture(0)`
with
`camera = config.get_camera()`

Line 41 replace
`ret, frame = capture.read()`
with
`frame = camera.read()`

**Comment by paviro** [comment]
Could you send a pull request?

**Comment by paviro** [comment]
Added thanks :)

**Comment by YaarPatandarAA** [comment]
Still having issues with 

File "/home/pi/MagicMirror/modules/MMM-Facial-Recognition-Tools-master/facerecognition_tester/facerecognition.py", line 42, in 
image = cv2.cvtColor(frame, cv2.COLOR_RGB2GRAY)
error: /build/opencv-ISmtkH/opencv-2.4.9.1+dfsg/modules/imgproc/src/color.cpp:3737: error: (-215) scn == 3 || scn == 4 in function cvtColor

**Comment by YaarPatandarAA** [comment]
Still having similar issues:

```
OpenCV Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /home/pi/opencv-2.4.9/modules/imgproc/src/color.cpp, line 3737
Traceback (most recent call last):
  File "facerecognition.py", line 42, in <module>
    image = cv2.cvtColor(frame, cv2.COLOR_RGB2GRAY)
cv2.error: /home/pi/opencv-2.4.9/modules/imgproc/src/color.cpp:3737: error: (-215) scn == 3 || scn == 4 in function cvtColor
```

Like @Try2Fly  I connected a USB Webcam and it works fine, I would prefer it to work with the PiCam.

**Comment by davelowelarsson** [comment]
Also experiencing issue with PiCam:

```
pi@raspberrypi:~/MMM-Facial-Recognition-Tools/facerecognition_tester $ python facerecognition.py
Loading training data...
ALGORITHM: LBPH
Training data loaded!
--------------------
Picam ausgewählt...
OpenCV Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /build/opencv-ISmtkH/opencv-2.4.9.1+dfsg/modules/imgproc/src/color.cpp, line 3737
Traceback (most recent call last):
  File "facerecognition.py", line 45, in <module>
    image = cv2.cvtColor(frame, cv2.COLOR_RGB2GRAY)
cv2.error: /build/opencv-ISmtkH/opencv-2.4.9.1+dfsg/modules/imgproc/src/color.cpp:3737: error: (-215) scn == 3 || scn == 4 in function cvtColor
```

**Comment by Patrick-Remy** [comment]
Same here, opened a new issue #11
