### ISSUE TITLE
error setting pixformat

### ISSUE THREAD

**Issue by tommibaer** [paviro/MMM-Facial-Recognition-Tools#7]
I got the following mistake after execute ther 4. step of the recognition-test-tool introduction

_4. Enter the tools/facerecognition_tester directory from a terminal and run python facerecognition.py._

```
pi@raspberrypi:~/MagicMirror/modules/MMM-Facial-Recognition-Tools/facerecognition_tester $ python facerecognition.py
Loading training data...
ALGORITHM: LBPH
Training data loaded!
libv4l2: error setting pixformat: Device or resource busy
HIGHGUI ERROR: libv4l unable to ioctl S_FMT
libv4l2: error setting pixformat: Device or resource busy
libv4l1: error setting pixformat: Device or resource busy
HIGHGUI ERROR: libv4l unable to ioctl VIDIOCSPICT

OpenCV Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /build/opencv-ISmtkH/opencv-2.4.9.1+dfsg/modules/imgproc/src/color.cpp, line 3737
Traceback (most recent call last):
  File "facerecognition.py", line 42, in <module>
    image = cv2.cvtColor(frame, cv2.COLOR_RGB2GRAY)
cv2.error: /build/opencv-ISmtkH/opencv-2.4.9.1+dfsg/modules/imgproc/src/color.cpp:3737: error: (-215) scn == 3 || scn == 4 in function cvtColor

```

Do somebody know why?

**Comment by paviro** [comment]
Please check http://forum.magicmirror.builders and come back if you are sure it is a bug :) I don't have a working mirror right now so I can't check :/

**Comment by GHLasse** [comment]
I get the same error. :-/

**Comment by swathi-ssunder** [comment]
@tommibaer , @GHLasse  - Does anyone of you know how to proceed after this error?  I get the same error. 
@paviro - I get this error even when I run `python facerecognition_tester` without Magic Mirror. Could you please help?

**Comment by swathi-ssunder** [comment]
I noticed that this error was only in the `tester`. When I used the module in the Magic Mirror, it seemed to work fine.

**Comment by paviro** [comment]
Same for the others? Only in the tester?

**Comment by paviro** [comment]
This maybe fixed now could you try?

**Comment by paviro** [comment]
Please reopen if not! :)
