### ISSUE TITLE
Cant recognize my camera.

### ISSUE THREAD

**Issue by MrPineMan** [paviro/MMM-Facial-Recognition-Tools#8]
![capture](https://cloud.githubusercontent.com/assets/17926205/19829156/010e4d3e-9dda-11e6-9d5a-2e0598a24ba5.PNG)

Hi Paviro,

I've some errors in the with my raspberry pi installing the tools. I've an USB and a Picam. But for both the same error. 

Are you able to help me? Or do you have some suggestions?
Python isn't my best language ^_^  

greets

**Comment by stantang986** [comment]
I got same errors for my usb camera

**Comment by paviro** [comment]
Have you tried doing what it says? Entering raspi-config and enabling it?

**Comment by MrPineMan** [comment]
Yes sure!

**Comment by MrPineMan** [comment]
I've done the installation multiple times, the reason in this Picture was the permissions. After the reinstall i clone the git Without sudo. That fixed the first lines.

**Comment by paviro** [comment]
So does it work now? Or is the camera thing still there?

**Comment by MrPineMan** [comment]
If i'm running the command : camera.capture in the terminal to test, it doesn't work neither ._.

**Comment by MrPineMan** [comment]
Errors still exist, busy for 2/3 weeks already more than 30 hours tryed to fix it haha. But worth it, it is a great feature to add :)

**Comment by MrPineMan** [comment]
http://imgur.com/a/kxxb1 
I can access the camera board on /dev/video0 by running the command:

sudo modprobe bcm2835-v4l2

**Comment by MrPineMan** [comment]
Fixed it, can be closed.

**Comment by paviro** [comment]
What was the problem?

**Comment by MrPineMan** [comment]
I wish i could tell you that, i fixed it for myself with a work around by using the convert (2) option> explained in another [(post.https://github.com/paviro/MMM-Facial-Recognition-Tools/issues/9)]

But i'm already fighting with a new error

## underline not related on this issue

@raspberrypi:~/MMM-Facial-Recognition-Tools/facerecognition_tester $ python facerecognition.py
Loading training data...
ALGORITHM: LBPH
Training data loaded!
Traceback (most recent call last):
  File "facerecognition.py", line 63, in <module>
    cv2.putText(frame, config.personen[label - 1], (x - 3, y - 8), cv2.FONT_HER$
IndexError: list index out of range

**Comment by paviro** [comment]
Have you added the names correctly?

**Comment by MrPineMan** [comment]
i've only added my own name? do i also have to add the default names? 
The following folders exist in training_data 
jd  negative  othername  vincent

my array looks like this: 

personen = ["vincent"]

RECOGNITION_ALGORITHM = 1

Ill test it with ["jd, negative, othernames, vincent"] Hold on.

**Comment by paviro** [comment]
Not sure to be honest not used the tester in a long time... just try to use the module directly there you only need your name :)

**Comment by MrPineMan** [comment]
Already fixed it, the correct line should be: 

personen = ['jd', 'negative', 'othernames', 'vincent']

But now i'm recognized as "othernames" . Its time to go into the real business :D Thanks for the help anyways.

**Comment by paviro** [comment]
This should also be fixed now :)
